version: 2.1

executors:
  default:
    docker:
      - image: "cimg/rust:1.58.1"

jobs:
  lint:
    executor: "default"
    steps:
      - "checkout"
      - run: "rustup component add clippy"
      - run: "cargo clippy"
  build:
    executor: "default"
    steps:
      - "checkout"
      - restore_cache:
          key: 'v1-cargo-lock-{{ checksum "Cargo.lock"}}'
      - run: "cargo build"
      - save_cache:
          key: 'v1-cargo-lock-{{ checksum "Cargo.lock"}}'
          paths:
            - "/usr/local/cargo/registry"
            - "target/"
  test:
    executor: "default"
    steps:
      - "checkout"
      - restore_cache:
          key: 'v1-cargo-lock-{{ checksum "Cargo.lock"}}'
      - run: "cargo --version"
      - run:
          name: "run tests"
          command: "cargo test -- --nocapture"
      - save_cache:
          key: 'v1-cargo-lock-{{ checksum "Cargo.lock"}}'
          paths:
            - "/usr/local/cargo/registry"
            - "target/"

workflows:
  version: 2
  run_test:
    jobs:
      - "lint"
      - "build"
      - "test"
